### ISSUE TITLE
Remove legacy API endpoint support

### ISSUE THREAD

**Issue by ajvb** [mozilla-services/iprepd#37]
There is code within iprepd that was meant to handle the switch to a new endpoint format, i.e.:
 https://github.com/mozilla-services/iprepd/blob/cd62a1f65e61ff91480ee07a0fa56232e2b471f8/http.go#L47-L62

We should be able to remove all of this now.

**Comment by ameihm0912** [comment]
Depends on https://github.com/mozilla-services/ip-reputation-js-client/issues/39
